### PR TITLE
demonstrate how to modify vocabulary

### PR DESCRIPTION
**Pull request by redthing1**
add some info on vocab modification

### CODE REVIEW

**Comment by 2shea** [comment]
This is definitely worth documenting. Not sure if it's better documented in the knausj README or the wiki. I'll see what the maintainers of that repository are thinking. 

If it does go in the wiki, we should link to it from somewhere, otherwise it's only discoverable by search (and the search functionality isn't stellar).

**Review by astropuffin — COMMENTED** [review]
Is `additional_words.csv` specific to knausj? Or does Talon itself know to pick that up?

**Comment by 2shea** [comment]
It's specific to knausj. It's referenced here: https://github.com/knausj85/knausj_talon/blob/master/code/vocabulary.py#L83. I don't think Talon has any awareness of that file.

**Comment by 2shea** [comment]
@xdrie We had some discussion, both in our semi-regular wiki video sync and the #talon-community slack where folks discuss maintenance of knausj repository, and we think this content makes more sense to live in the README of https://github.com/knausj85/knausj_talon. Would you like to open a PR against that README or is it OK for one of us to do it for you?

**Comment by xdrie** [comment]
It is ok for u to do! I am quite busy

**Comment by AndrewDant** [comment]
@2shea is there an issue or pull request for this to be added to knausj? If so we can probably close this PR.

**Comment by splondike** [comment]
I don't see anything in knausj, it just needs somebody to get around to it. Maybe you :)?

**Comment by C-Loftus** [comment]
This is stale and can probably be closed in light of the refactor

**Pull request closed without merging**
