### PR TITLE
Add Joystick / Gamepad Info

### PR DESCRIPTION
**Pull request by C-Loftus**
Joysticks/Gamepads are supported in Talon beta but have relatively little documentation currently. This commit adds some resources for general controller usage as well as technical details needed for users to use custom controllers. I have confirmed all this info myself talking to aegis while developing my own custom controller.

I also rearranged the order of  the Windows Login paragraph to have it flow better.

### CODE REVIEW

**Comment by C-Loftus** [comment]
I will clarify as well, even though this is in the beta, I think it is useful to document this as there isn't much public info currently (I think it helps others develop more gamepad resources anyways once it has more publicity) and it seems reasonable that it may one day be merged into the public release. The technical details regarding XInput and SDL are unlikely to change given the underlying gamepad library being used by Talon.

**Comment by phillco** [comment]
I think gamepad support shipped to public in 0.4, it's just Stream Deck support that is still in beta, FWIW.

**Comment by C-Loftus** [comment]
You are totally right, just checked on. I updated the commit to remove the beta info and added a bit more info

**Review by 2shea — APPROVED** [review]
Thank you @C-Loftus @phillco!! 💯 ❤️

**Pull request merged**
