### PR TITLE
Make the font larger and darker for readability/accessibility.

### PR DESCRIPTION
**Pull request by rntz**
The default font color it is too light, which makes it hard to read. It's also pretty small.

This pull request changes the default colour to black, and uses the browser's default font-size settings.

Unfortunately, the default CSS style hard-codes font size (and color?) in several places. This only adjusts the font size and color for default text and code fragments, but at least it's a start.

### CODE REVIEW

**Comment by 2shea** [comment]
if we end up fighting against the custom theme too much, we can swap it out for something else.

**Comment by 2shea** [comment]
@rntz I ended up building the custom theme directly in the repository to patch an issue. When you get a chance, can you confirm your changes are still being applied as expected? I think they are, but want to make sure.
 https://github.com/TalonCommunity/Wiki/commit/b336dcd8d841b3ad08d7aa23a6fddbe62447b6e7

**Comment by 2shea** [comment]
Let me know if anything doesn't look right.

**Comment by rntz** [comment]
I took a look at talon.wiki and it looks fine to me!

**Pull request merged**
