### PR TITLE
Wiki Refactor

### PR DESCRIPTION
**Pull request by C-Loftus**
- [x] Remain website categories to quickstart, basic usage, and customization
- [x] Refactor about logo / remove official talon trademarked stuff
- [x] Think about visual design and landing page
- [x] Add precommit for formatter
- [x] Set up precommit

### CODE REVIEW

**Comment by C-Loftus** [comment]
@2shea If you need help adding the pre-commit CI just let me know. Should be another github integration. Other than that the categorization should be all set. Just visual styling needs to be done now.

**Comment by C-Loftus** [comment]
I changed the landing page back to the simple logo. @AndreasArvidsson made a good point in the cursorless meetup today that we don't want to try and make this out to be the official landing page for talon. So probably best to keep it similar and enumerate what the community has, not necessarily talon itself

**Comment by AndreasArvidsson** [comment]
> I changed the landing page back to the simple logo. @AndreasArvidsson made a good point in the cursorless meetup today that we don't want to try and make this out to be the official landing page for talon. So probably best to keep it similar and enumerate what the community has, not necessarily talon itself
> 
> Anyone who sees this, please vote on slack for the new logo

I think it fine to talk about some Talon concepts like modules and contexts and so on, but I think we should try to avoid the sales pitch and just focus on actually using talon and the community repo.

**Comment by C-Loftus** [comment]
> I think it fine to talk about some Talon concepts like modules and contexts and so on, but I think we should try to avoid the sales pitch and just focus on actually using talon and the community repo.
Yup I am in agreement. I will clean up the `Unofficial Talon Docs` once we have merged the visual changes and finished the docusaurus refactor

**Comment by C-Loftus** [comment]
New logo was decided based on a community vote has been added. Think this is all set to merge into staging once we have precommit setup.

**Comment by saidelike** [comment]
I propose the following changes:

initial text 
> Talon enables people who have limited use of their hands or want to stop using their hands to write code, play video games, and in general have unrestricted use of their computer. 

replacement
> Talon enables people who have limited use of their hands or want to stop using their hands to navigate the web, dictate text, play video games, write code and in general have unrestricted use of their computer.

**Comment by saidelike** [comment]
> Some of this content exists temporarily until the official Talon Docs are created.
The above could be removed.

I propose this change:

Initial text
> Unofficial Talon Docs

Replacement:
> Talon concepts and programming

**Comment by C-Loftus** [comment]
@saidelike Totally agree with all those types of edits. Right now this specific PR is just editing format and higher level structure. So we don't lose any of your feedback, feel free to make issues that reference line numbers or you can also make PR's against staging branch: https://github.com/TalonCommunity/Wiki/tree/staging 

The wiki in general right now is too verbose. We will need to make a fair amount of  those types of edits you propose. I will be splitting a lot of stuff up into better hierarchies and grouping them better with tags.

**Comment by C-Loftus** [comment]
Merging this into staging. All the files are formatted properly with precommit and the landing page and logo are finished.

**Pull request merged**
