### PR TITLE
remove mention of bind mounting for linux

### PR DESCRIPTION
**Pull request by 2shea**
Per request from Ryan, remove the suggestion of bind mounting on Linux in the Troubleshooting doc.

### CODE REVIEW

**Comment by C-Loftus** [comment]
Thanks for doing this I could've gotten to it, but I appreciate it

**Comment by 2shea** [comment]
@C-Loftus I needed to test that I didn't break the netlify integration for the old Jekyll site, so I went ahead and made the PR. It would be helpful if you could make sure this change gets ported over to the new refactor version if you are willing/able!

**Comment by C-Loftus** [comment]
Yes I will make sure to do that

**Comment by C-Loftus** [comment]
Addressed in most recent commit on staging PR

**Pull request merged**
