### PR TITLE
Algolia search

### PR DESCRIPTION
**Pull request by C-Loftus**
Can't test this locally, assume it will work since the setup is pretty easy, just added in config options.

There is an API key committed here but it is meant to be public.

### CODE REVIEW

**Review by 2shea — APPROVED** [review]
Excited to see how it works!

**Comment by C-Loftus** [comment]
This is not working unfortunately. Going to revert.  @pokey do you happen to recall if you had to do anything special to get algolia set up for you with cursorless? I followed all the docs from what I can see. Not sure what's wrong. I can't manually trigger crawls on the free plan but I imagine it should have been crawled. I made this account a week or so ago.

**Comment by pokey** [comment]
Maybe have a look at cursorless algolia config to see if it's different at all?

Do you get any logs either in algolia console or in chrome dev tools when you try to search?

Does anything appear in your algolia index? You should be able to see how many docs had been indexed

I vaguely remember we had to wait for a week or something for them to activate something

**Comment by C-Loftus** [comment]
> Maybe have a look at cursorless algolia config to see if it's different at all?

Seems the same

> Do you get any logs either in algolia console or in chrome dev tools when you try to search?

Nope unfortunately

> Does anything appear in your algolia index? You should be able to see how many docs had been indexed

Nothing at the moment even though I created it and activated the app, with confirmation from support. Perhaps I need to wait a bit longer for a crawl. I don't control crawl times in the free plan unfortunately. 

> I vaguely remember we had to wait for a week or something for them to activate something

Fair. I will wait a bit longer. I also emailed support on their side, so hopefully will resolve this in the next couple days

**Comment by pokey** [comment]
Anything in the algolia index yet / any word back from support?

**Pull request merged**
