### PR TITLE
Document using talon with nix

### PR DESCRIPTION
**Pull request by C-Loftus**
Initial documentation for using Talon with Nix the package manager and/or NixOS

### CODE REVIEW

**Comment by C-Loftus** [comment]
@fidgetingbits Started this as a draft. 

Do you think this should include installation instructions (i.e. something like the following which works for me)

```nix
  environment.systemPackages = with pkgs; [
    # vim
    (builtins.getFlake "github:nix-community/talon-nix").packages.${builtins.currentSystem}.default
    #  wget
  ];
```

I realize that a lot of nix configs look a bit different so not sure if this is out of scope and better left up to external docs? 

I named the section `Non-Standard Usage` to emphasize that this is not an official package. But open to other ideas on naming.

**Comment by fidgetingbits** [comment]
Thanks for starting this. I'll add some stuff later. I think it's probably okay to show how to install/enable it ya. Given users are likely wanting to reduce typing already, giving copyable instructions to get it running asap seems useful. But ya, nix gives lots of options how to do things so have to decide what is worth showing..

I think I would just list the most common scenarios:

- Adding to a non-flake config (as you showed above) directly into packages
- Adding to a flake-based config as an input, and then using it
- Should show how to import it and then enable it via the exposed option (`programs.talon.enable = true`) instead of directly adding as a package too. I think the this is maybe preferred in that it also has a `services.udev.packages = [ pkgs.talon ];` statement once enabled, but I'll have to double check if that's actually required to use the tobii... 

I do have a PR up now for allowing overrides in talon-nix, so can add something about using the beta once that gets upstreamed.

**Comment by fidgetingbits** [comment]
I sent a PR to your branch to add my changes https://github.com/TalonCommunity/Wiki/pull/290

**Comment by fidgetingbits** [comment]
Also I'm not sure what the best name for "non-standard usage" is either. "Exotic Linux Distributions"? Usage implies (to me) how talon is being used, not how it's installed, so not really sure... I'm good with whatever though if can't think of something better.

**Comment by C-Loftus** [comment]
Closing in favor of new PR

**Pull request closed without merging**
