### PR TITLE
Add foot pedal options

### PR DESCRIPTION
**Pull request by 2shea**
Some Talon users find it useful to incorporate foot pedals into their workflow. This PR adds a section about foot pedals which includes a few more commonly used foot pedals.

### CODE REVIEW

**Review by C-Loftus — COMMENTED** [review]
A few things that would be good to mention

-  Kinesis Savant Elite 2  is mechanical and has adjustable tension
    - this pedal can remap keys at the hardware level
 -  Might be useful to say a bit regarding the fact that the customization needed for foot pedals  is generally more intensive than just talon files. 
     -  (ie you need to know the talon ctx python api  decently well,  and the fact that certain actions don't work well with talon hotkeys. For instance, the user.vscode Knausj commands have timeout issues if read  asynchronously. )
     -   When customizing you need to use cron  and asynchronously reading a state dictionary if you want to bind pressing two pedals at once  
  
   That being said I think emphasizing foot pedals is really good since they make scrolling so much easier.

**Comment by 2shea** [comment]
@C-Loftus Thanks for the feedback! I've pushed an edit incorporating your comments. If you have time, let me know if it looks ok.

**Review by C-Loftus — COMMENTED** [review]
I think that edit looks good to me.  As I read over what I recommended again, perhaps it is a bit specific towards my experience with the kinesis savant,  but from what I have seen with Andreas's code,  I think it is relatively representative of other foot pedal users too. 

Perhaps in a month or two as I continue to use my pedal (I just got it a few weeks ago), I will submit another pull request on this with some updated information if I think of anything else.

**Comment by 2shea** [comment]
@C-Loftus sounds good! I'll go ahead and merge as-is. It can always be updated later, and what's in this PR is better than what existed previously, which was no mention of foot pedals at all.

Later PR's definitely welcome as you learn more!

**Pull request merged**
